### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by akolarck** [planeur-net/airspace#12]
Great job maintaining this Github project, guys! 

For the sake of transparency - please consider doing Releases on Github. Similar to what you were doing all the time when you were sending files by email. Each time you think that fixes are stable, create a release for France22-6,txt/cub. 

https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

That way the master branch can always be work in progress and there is no risk to distribute an intermediate version to the SeeYou community.

Thanks!

**Comment by llauner** [comment]
Hi
We're using a different approach:
- The master branch is supposed to be the latest stable version.
- The work in progrss is done in a branch

When pushed to master, the corresponding .cub file is automatically generated and published to github pages.
The france.txt and france .cub files are available here:
https://planeur-net.github.io/airspace/france.txt
https://planeur-net.github.io/airspace/france.cub

The use of git to manage the airspace file is a relatively new concept to the current team. We could add the notion of release in the future if really needed once everyone is fluent on the git process.

Hope this helps

**Comment by snip** [comment]
@llauner what is missing in current setup is something to explicitly say what version this file is coming from.
Maybe a git tag is not enough for that.
But maybe the build mechanism can incorporate a field as comment in the file with the released version? Something like including date + time + hash of last commit?

**Comment by llauner** [comment]
@snip You're right.
I've created the issue for that : #23
