### ISSUE TITLE
Add version information in txt file

### ISSUE THREAD

**Issue by llauner** [planeur-net/airspace#23]
@llauner what is missing in current setup is something to explicitly say what version this file is coming from.
Maybe a git tag is not enough for that.
But maybe the build mechanism can incorporate a field as comment in the file with the released version? Something like including date + time + hash of last commit?

_Originally posted by @snip in https://github.com/planeur-net/airspace/issues/12#issuecomment-1308606924_

**Comment by llauner** [comment]
@snip 
I've just created a github action to do just that:
https://github.com/planeur-net/airspace/pull/24

The action will automatically add a version at the top of the file. It will look like this:
*version= 6c37385 2022-10-27 19:09:49 +0200

Where 6c37385 is the latest commit for france.txt + date

**Comment by snip** [comment]
Nice ! 
Thanks.
