### ISSUE TITLE
LF P 26 Gravelines misplaced

### ISSUE THREAD

**Issue by reskume** [planeur-net/airspace#25]
Hi,

not sure on how to submit valid PR (just change france.txt and do PR? - If so, will do next time) so I'm opening a ticket for this one. One of our openaip users found that LF-P 26 Gravelines is misplaced. According to official eAIP, the correct definition should be:

```text/plain-text

** P 26 GRAVELINES (08 APR 2010) **
AC P
AN P26 Gravelines
AH 3300FT MSL
AL GND
V X=51:00:52 N 002:08:00 E
DC 2.7

```

**Comment by lordfolken** [comment]
You can edit the file right on github. It will ask you to create a branch and a PR.

**Comment by llauner** [comment]
@reskume Sure, as @lordfolken mentioned, if you can submit a pull request, and add the link to the document specifying the right coordinates that would be great.
Thanks
Ludovic
