### ISSUE TITLE
TMA de CHAMBERY

### ISSUE THREAD

**Issue by snip** [planeur-net/airspace#31]
Les TMA de Chambéry sont classées en D et déclassées en E de mi-avril à mi-décembre.

![image](https://user-images.githubusercontent.com/466133/236305570-20738a02-e756-4077-9ae1-ce2907c57bc1.png)

Hors dans le fichier on voit ces TMA en E.
```
** TMA CHAMBERY Partie 1 (2021/04/22) **
AC E
AY TMA
AN TMA CHAMBERY 1 CHAMBERY INFO 123.7 CLASSE E de mi-avril  mi-decembre et du lundi 11h UTC au jeudi soir
AH FL095
AL 3000FT MSL
AF 123.700
DP 46:02:56 N 006:09:33 E
DP 45:59:06 N 006:14:32 E
DP 45:50:49 N 006:05:02 E
DP 45:47:15 N 006:03:22 E
DP 45:40:50 N 005:57:18 E
DP 45:38:07 N 005:57:18 E
DP 45:36:20 N 005:58:58 E
DP 45:29:26 N 005:58:48 E
DP 45:29:25 N 005:46:30 E
DP 45:43:38 N 005:44:47 E
DP 45:54:07 N 005:45:29 E
V D=-
V X=46:03:03 N 005:47:12 E
DB 45:54:07 N 005:45:29 E,45:55:41 N 005:54:39 E
DP 45:55:41 N 005:54:39 E
DP 46:02:56 N 006:09:33 E

** TMA CHAMBERY Partie 2 (2020/12/03) **
AC E
AY TMA
AN TMA CHAMBERY 2 CHAMBERY INFO 123.7 CLASSE E de mi-avril  mi-decembre et du lundi 11h UTC au jeudi soir
AH FL95
AL 5500FT MSL
AF 123.700
DP 45:58:31 N 005:36:01 E
V D=-
V X=46:03:03 N 005:47:12 E
DB 45:58:31 N 005:36:01 E,45:54:07 N 005:45:29 E
DP 45:54:07 N 005:45:29 E
DP 45:43:38 N 005:44:47 E
DP 45:29:25 N 005:46:30 E
DP 45:29:25 N 005:43:04 E
DP 45:34:54 N 005:31:41 E
DP 45:51:22 N 005:27:02 E
DP 45:55:00 N 005:29:08 E
DP 45:58:31 N 005:36:01 E

** TMA CHAMBERY Partie 3 (2021/04/22) **
AC E
AY TMA
AN TMA CHAMBERY 3 CHAMBERY INFO 123.700 CLASSE E de mi-avril  mi-decembre et du lundi 11h UTC au jeudi soir
AH FL115
AL FL095
AF 123.700
DP 45:52:20 N 006:06:46 E
DP 45:49:44 N 005:34:52 E
DP 45:43:00 N 005:29:22 E
DP 45:41:08 N 005:29:53 E
DP 45:38:07 N 005:57:18 E
DP 45:40:50 N 005:57:18 E
DP 45:47:15 N 006:03:22 E
DP 45:50:49 N 006:05:02 E
DP 45:52:20 N 006:06:46 E
``` 
Alors que les CTR CHAMBERY 3 et CTR CHAMBERY 2 sont en D dans le fichier alors qu'elles ont un coportement proche des TMA.
```
** CTR CHAMBERY 2  MI-DEC -> MI-AVRIL (2023/04/20) **
AC D
AY CTR
AN CTR CHAMBERY 2  118.3  ACTIVE mi-dec -> mi-avril
AH 3500FT MSL
AL GND
DP 45:46:38 N 005:50:00 E
DP 45:46:38 N 005:52:14 E
DP 45:45:05 N 005:53:10 E
DP 45:45:04 N 005:50:00 E
DP 45:46:38 N 005:50:00 E

** CTR CHAMBERY partie 3 (2020/12/03) **
AC D
AY CTR
AN CTR CHAMBERY 3 CHAMBERY TOUR 118.3 ACTIVABLE de mi-decembre  mi-avril
AH 1000FT AGL
AL GND
AF 118.300
DP 45:36:05 N 005:50:00 E
DP 45:36:05 N 005:49:00 E
DP 45:32:00 N 005:49:00 E
DP 45:30:10 N 005:47:20 E
DP 45:30:10 N 005:48:20 E
DP 45:31:45 N 005:50:00 E
DP 45:36:05 N 005:50:00 E
```

Ne faudrait il pas traiter les TMA en D avec le commentaire en exception ? Ou en tout cas traiter les CTR hivernales d'une façon similaire aux TMA ?

Je ne retrouve pas l'info officielle actuelle du déclassement en E.
Mais j'ai ce vieux fichier lors des modifications.
[Plaquette info changement espaces Chambéry.pdf](https://github.com/planeur-net/airspace/files/11400665/Plaquette.info.changement.espaces.Chambery.pdf)

Il y a également cet ancien SUP AIP.
[TMA LFLB Sup AIP 198.20 .pdf](https://github.com/planeur-net/airspace/files/11400673/TMA.LFLB.Sup.AIP.198.20.pdf)

Merci

**Comment by snip** [comment]
La source des infos (Merci Cedric)

pour les CTR :
https://www.sia.aviation-civile.gouv.fr/dvd/eAIP_20_APR_2023/FRANCE/AIRAC-2023-04-20/html/eAIP/FR-AD-2.LFLB-fr-FR.html#LFLB-AD-2.17
<img width="535" alt="image" src="https://user-images.githubusercontent.com/466133/236647769-dbffc4fb-b2c8-4e7e-b1a4-f5abf43784cf.png">


Et pour les TMA : 
https://www.sia.aviation-civile.gouv.fr/dvd/eAIP_20_APR_2023/FRANCE/AIRAC-2023-04-20/html/eAIP/FR-ENR-2.1-fr-FR.html#ENR-2.1
<img width="521" alt="image" src="https://user-images.githubusercontent.com/466133/236647728-33051550-e008-4df4-9fa1-9877628c55d7.png">

**Comment by jp1536** [comment]
Le choix de classement en E des TMA est cohérent avec la saison vélivole, celui de laisser en D les CTR correspond à une volonté d'éviter des vols de planeurs dans les circuits VFR de la vallée de Chambery. C'est un choix de la FFVP pour éviter un durcissement des conditions d'accès des TMA.
