### ISSUE TITLE
Héberger les aérodromes, champs vachables et points de virage français

### ISSUE THREAD

**Issue by mlep** [planeur-net/airspace#40]
XCSoar distribue l'espace aérien français en pointant vers https://planeur-net.github.io/airspace/france.txt (voir https://github.com/XCSoar/xcsoar-data-content/blob/master/data/remote/airspace/country/FR-ASP-National-PlaneurNet.txt.json).

Actuellement, XCSoar héberge un fichier de points de virage pour la France (https://github.com/XCSoar/xcsoar-data-content/blob/master/data/content/waypoint/country/FR-WPT-National-XCSoar.cup). Il contient des aérodromes, des champs vachables, et des points de virages.
Ce fichier pourrait être hébergé sur un dépôt de planeur-net, ce qui permettrait :
- d'avoir un hébergement indépendamment d'un logiciel particulier (même si j'aime bien XCSoar :smile: )
- de donner plus de visibilité à ce fichier, et donc d'attirer des contributeurs
- de mettre à jour, puis maintenir ce fichier
- éventuellement de séparer aérodromes, points de virage et champs vachables

**Comment by llauner** [comment]
Désolé, je viens seulement de voir ton message.
Pourquoi pas...tu es pret a contribuer ?
Pour la partie champs vachables, je vois l'intérêt. Pour la partie points de virage, je vois moins l'intérêt ...

Mais on peut en discuter. Tu peux m'envoyer un email pour en discuter ? ludovic.launer@gmail.com

**Comment by llauner** [comment]
@mlep Le problème que je vois et pour maintenir de façon collaborative la version .cupx du fichier (avec des images). Etant donne que le format est binaire, cela devient difficile de comparer ce qui est ajoute / modifie d'une version a l'autre.
Cela marche pour le format .cup, mais on pert en information et donc en intérêt...
A discuter ...

**Comment by llauner** [comment]
@mlep 
On peut effectivement lancer un repo...je vais regarder ca, les vacances de noel sont pour bientot...
Peut etre le mieux serait de modifier le cupx et d'en extraire automatiquement le .cup...a voir mais il doit exister qqchose pour faire ca.
Pour les aerodromes il faudrait la meme chose que ce que tu donnes, mais qui fabrique le .cupx. Le probleme etant que le format cupx n'est pas publie....donc ca risque d'etre complique...
Mais on peut peut etre utiliser le script perl dont tu parles pour extraire regulierement les terrains...faut que je regarde.

Sinon quel est ton nom ? tu voles ou ?
Cordialement
Ludovci

**Comment by llauner** [comment]
https://github.com/planeur-net/outlanding
