### ISSUE TITLE
Zone AC unclassified

### ISSUE THREAD

**Issue by delta217** [planeur-net/airspace#43]
XCsoar ne gère pas çà ? je suis en 7.41

Pourtant, dans le forum planeur.net, tu avais écrit :
"Je confirme que ce format est bien reconnu par SeeYou, SeeYou Navigator et XCSoar"

Et là, j'ai tout en bleu ?
Tu vas me dire que XCSoar, c'est pas ton truc, mais tu as bien une petite idée ?

Il me semble qu'en 2023 j'avais modifié toutes les lignes AC...

**Comment by llauner** [comment]
Tu as un exemple ?
Qu'est ce que tu entends par "ne gere pas ca ?"

Sinon il faut aller voir dans les parametres de XCSoar pour faire changer les couleurs:
![image](https://github.com/planeur-net/airspace/assets/32835597/3c080294-6d2e-472c-89e3-ffcbae3fb899)

Je n'utilises plus XCSoar, mais je sais que c'est tres utilise, donc je reste pragmatique et realiste: il faut un support XCSoar.
Par contre je n'utilise toujours pas de clavier francais avec les accents ;)

**Comment by llauner** [comment]
C'est ca que tu ne vois pas ?
![image](https://github.com/planeur-net/airspace/assets/32835597/0db79615-a889-4ca0-9c22-78ea9444d724)

Pas besoin de bidouiller le fichier c'est de la conf de XCSoar

**Comment by delta217** [comment]
Typiquement, en l'état, presque tout sort en bleu-cyan, ou pas : 

![Screenshot_20240201_2](https://github.com/planeur-net/airspace/assets/154979750/56a5859a-fec6-42e4-b115-f2f0157d6baf)

Les R sont : 
AC UNCLASSIFIED
AY R

Les écrins sont : 
AC UNCLASSIFIED
AY P

Les "passages" dans les écrins sont : 
AC G
AY W
et ils n'apparaissent pas.

A l'inverse, le FL 115 max de Sisteron passe bien (en bleu profond) : 
AC D
AY UNCLASSIFIED

Alors que l'année dernière, j'arrivais (en modifiant quelques lignes avoir les couleurs qui allaient bien - je mettais la R196 en classe A...), çà : 

![Screenshot_20240201_21](https://github.com/planeur-net/airspace/assets/154979750/f1ad4a60-68ad-4891-98d9-bbd429afce6f)

**Comment by delta217** [comment]
Pas bossé sur la frontière italienne aujourd'hui...

**Comment by llauner** [comment]
Iil faut que tu modifie les couleurs dans les paramètres pour avoir ce que tu souhaites.

>Les "passages" dans les écrins sont :
>AC G
>AY W
>et ils n'apparaissent pas.

La je comprends pas: je les vois sur ta capture d'ecran:
![image](https://github.com/planeur-net/airspace/assets/32835597/e51e1a5a-388b-4931-ad0c-400503aee56f)
Tu as change la classe a la main ?
Pas besoin de faire ca, regardes:
![image](https://github.com/planeur-net/airspace/assets/32835597/a78a0e64-4091-4538-b51b-07ce0dcbcce4)
Est ce que tu as mis une couleur pour la classe G dans les parametres ?
![image](https://github.com/planeur-net/airspace/assets/32835597/075a7289-6608-403c-aacd-2773f35298a9)

**Comment by delta217** [comment]
> La je comprends pas: je les vois sur ta capture d'ecran:

Oui, c'est mon bidouillage de l'année dernière (en effet, changé à la mimine des classes comme la R196, les Ecrins), mais bonne idée que de mettre une couleur sur la classe G, merci.

Par contre, j'ai bien du rouge sur les classes R et P, et çà sort en bleu-cyan ? 
J'ai mis du vert sur la classe A pour planquer la R196

![20240202_104420_temp](https://github.com/planeur-net/airspace/assets/154979750/91a308b6-56ae-4177-9211-4d8cfff9e204)

**Comment by llauner** [comment]
> Par contre, j'ai bien du rouge sur les classes R et P, et çà sort en bleu-cyan ? J'ai mis du vert sur la classe A pour planquer la R196

Ah ben justement, R et P ce ne sont pas des classes dans le format extended qui est utilise.
Les classes AC sont A,B,C,D,E,F,G
Ensuite il  a le type AY: 
http://www.winpilot.com/UsersGuide/UserAirspace.asp
![image](https://github.com/planeur-net/airspace/assets/32835597/81d2ebb6-db81-4157-a62c-c22b00760d76)

**Comment by delta217** [comment]
> Le AC au dessus du AY est surement en UNCLASSIFIED dans ces cas la.

Tout à fait, comme indiqué plus haut, mais comment faire alors, puisque le unknown en AC prime sur le R en AY ?

**Comment by delta217** [comment]
Ben, en plus, j'ai une couleur sur la classe G (rouge !), donc les voies dans les écrins devraient sortir ?

![20240202_113548_temp](https://github.com/planeur-net/airspace/assets/154979750/0d076b37-144e-4cbd-b0f2-47084f904522)

**Comment by llauner** [comment]
C'est bien en couleur chez moi:
![image](https://github.com/planeur-net/airspace/assets/32835597/3b00298d-d832-4bba-bc6b-f5c6f6668251)
![image](https://github.com/planeur-net/airspace/assets/32835597/5a0b1aee-3b01-4216-af76-3fa9dc4f558e)

Tu as la derniere version de XCSoar ?
Derniere version du france.txt ?

**Comment by delta217** [comment]
Version 7.41 et j'ai essayé 3 fichiers : 
- depuis github
- téléchargement direct FR-ASP-National-PlaneurNet.txt
- téléchargement direct FR-ASP-National-OpenAIOt.txt

**Comment by llauner** [comment]
> Version 7.41 et j'ai essayé 3 fichiers :

OK

> * depuis github
> * téléchargement direct FR-ASP-National-PlaneurNet.txt

Ca c'est le meme fichier. C'esst celui de ce repo.
Par contre pour le FR-ASP, je pense que pour qu'il soit a jour il faut le supprimer et le remettre. Pas certain...

> * téléchargement direct FR-ASP-National-OpenAIOt.txt

Ca je sais pas comment et quand c'est mis a jour...

**Comment by llauner** [comment]
On a pas la meme configuration, y'a pas de raison.
T'es alle voir dans les filtres des Airspace ? par defaut je crois que la classe G est pas affichee.
![image](https://github.com/planeur-net/airspace/assets/32835597/f67d5712-cf3d-4a01-939e-05c8d4f0827f)

**Comment by delta217** [comment]
Gagné pour la classe G, on progresse...

![20240202_classeG](https://github.com/planeur-net/airspace/assets/154979750/d8ac674e-c808-49e2-8c48-ceb728542a20)

**Comment by delta217** [comment]
Et si je met (à la mimine) GP à la place de UNCLASSIFIED ligne AC, je retrouve ma vue de l'année denière : 

![20240202_GP](https://github.com/planeur-net/airspace/assets/154979750/8725beab-f201-4d77-a9d4-df7a86217283)

Il reste les P et les R...
Le cercle rouge vient d'un fichier spécifique que j'ai fait au fil des NOTAM

**Comment by llauner** [comment]
Oui sauf que ce n'est pas le format openair extended.
Le mieux serait de faire une issue dans XCSoar pour avoir une meilleur support du format.

**Comment by delta217** [comment]
Issue 1341...

**Comment by llauner** [comment]
Oui mais je crois que ce que tu decris c'est pas le probleme.
Le probleme c'est plutot comme je le decris = quand tu as AC UNCLASSIFIED, et bien il ne prend pas en compte les indications dans le AY.
Seul le AC xx est pris en compte. et pas le AY yyy

**Comment by delta217** [comment]
C'est la différence entre les propos d'un amateur et ceux d'un professionnel...
Cela dit, je décris un résultat qui est juste (sans chercher à remonter à la cause).

**Comment by llauner** [comment]
See: https://github.com/XCSoar/XCSoar/issues/1340

**Comment by llauner** [comment]
On dirait que le sujet avance chez XCSoar il y a une PR en route:
https://github.com/XCSoar/XCSoar/pull/1349

**Comment by delta217** [comment]
Excellent !Bravo maître...Envoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : Ludovic ***@***.***> Date : 16/02/2024  09:29  (GMT+01:00) À : planeur-net/airspace ***@***.***> Cc : Jean-Philippe ***@***.***>, Author ***@***.***> Objet : Re: [planeur-net/airspace] Zone AC unclassified (Issue #43) 
On dirait que le sujet avance chez XCSoar il y a une PR en route:
XCSoar/XCSoar#1349
