### ISSUE TITLE
Airspace Frequencies not listed as AF

### ISSUE THREAD

**Issue by lordfolken** [planeur-net/airspace#7]
Hello, 

The winpilot standard, has been extended to have a field for the Frequency of an Airspace named 'AF'. 

Several pieces of software can already interpret this and control the radio with it.

**Comment by llauner** [comment]
Hi
If you can provide the information in some format (CSV, text, other ...), then maybe I go go ahead and add the information into the file.
Alternatively, you can add the information and submit a pull request.
Regards,
Ludovic

**Comment by llauner** [comment]
OK, well, I can add the information if I have it, but I don't have time to find the frequencies for each airspace.
I guess this will stay pending until we can find someone who can provide the aggregated information to be fed into the file...

**Comment by llauner** [comment]
I wrote a quick parser that adds the rdaio frequency when it's available in the airspace name. I've just submitted a pull request:
https://github.com/planeur-net/airspace/pull/14

**Comment by llauner** [comment]
Info has been added into the currentfile.
