### ISSUE TITLE
Github action for PRs fails due to "npm audit"

### ISSUE THREAD

**Issue by reskume** [planeur-net/airspace#71]
A github action is run for PRs that validates the submitted OpenAIR using the OpenAIP openAIR parser. The scripts fails due to a "npm audit" that has a security issue as a result. I updated the parser which needed some pkg updates.

**Comment by llauner** [comment]
it looks like the npm audit thing is a warning only...I'll try to run this manually to see where the error is coming from ...

**Comment by llauner** [comment]
I ran openaip-openair-parser manually.
It looks like there's an unsupported comment being used:
Error found at line 36234: Failed to read line 36234. Unknown syntax.
That's the line with the ###

![image](https://github.com/user-attachments/assets/b597cd32-64f3-48f3-979b-be2b340cbcdc)

**Comment by reskume** [comment]
fixed

Am Di., 16. Juli 2024 um 08:57 Uhr schrieb Ludovic ***@***.***
